### ISSUE TITLE
new file details 

### ISSUE THREAD

**Issue by Kayuemkhan** [rommansabbir/CacheX#1]
Does CacheX Create a new file for me everytime? 
Does the name are same?

**Comment by rommansabbir** [comment]
No, It doesn't create .xml file every time, It will be created if not exist.

**Comment by Kayuemkhan** [comment]
Aren't you dealing with the cacheX like Sharedpreferences ?

**Comment by rommansabbir** [comment]
Yes, CacheX use SharedPref as its storage.

**Comment by Kayuemkhan** [comment]
Then, I was asking that CacheX Create a new file for me everytime?
Does the name are same?

Because, SharedPreferences is creating a file!

**Comment by rommansabbir** [comment]
I'm using this library in my personal work, even in production too. Working well without any kind of issue.
